---
# This automation simulates the use of the IKEA TRADFRI Dimmer control
# connected through ZHA.

blueprint:
  source_url: https://github.com/iresten/pkv-ha/blob/main/zha_ikea_trafri_2button_open_close_hold_custom.yaml

  name: IKEA TRADFRI - 2 Button Remote Open/Close - Custom Actions (Hold) (iresten)

  description: >-
    This automation simulates the use of the IKEA TRADFRI open/close switch
    connected through ZHA.

  domain: automation

  input:
    remote:
      name: IKEA TRADFRI open/close remote control
      description: Select the remote control you wish to use.
      selector:
        device:
          filter:
            - integration: zha
              model: TRADFRI open/close remote
    up_open:
      name: Short Press open button
      description: The action to perform on Short Press of the open Button
      selector:
        action:
      default: []
    down_close:
      name: Short Press close button
      description: The action to perform on Short Press of the close Button
      selector:
        action:
      default: []
    open_long:
      name: Long Press open button
      description: The action to perform on Long Press of the open Button
      selector:
        action:
      default: []
    close_long:
      name: Long Press open button
      description: The action to perform on Long Press of the open Button
      selector:
        action:
      default: []

mode: single
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - choose:
      # Short-Press the open button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "up_open" }}'
        sequence: !input up_open

      # Short-Press the close button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "down_close" }}'
        sequence: !input down_close

    # Any other event will cancel the repeat loops (i.e. releasing the [on|off] button)
    default: []
